name: ssl
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - python=3.11.7
  - pip
  - pip:
    - tf-gpu==2.11.0
    - keras
    - librosa
    - numpy
    - pandas
    - pytz
    - scikit-learn
    - scipy
    - soundfile
    - tensorboard
    - tensorflow-probability
    - tqdm
